/**
 * generated by Xtext 2.14.0
 */
package asmeta.avallaxt.tests.syntax;

import asmeta.avallaxt.avalla.Element;
import asmeta.avallaxt.avalla.Scenario;
import asmeta.avallaxt.avalla.Set;
import asmeta.avallaxt.tests.AvallaInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AvallaInjectorProvider.class)
@SuppressWarnings("all")
public class AvallaXtParsingSetTest {
  @Inject
  private ParseHelper<Scenario> parseHelper;

  @Test
  public void set() {
    this.test("x", "10");
    this.test("x ", "10");
    this.test("x(yy)", "z+3");
  }

  @Test
  public void setWithStrings() {
    this.test("x(8)", "\"good\"");
    this.test("x(\"good\")", "\"good\"");
  }

  public void test(final String location, final String value) {
    try {
      InputOutput.<String>println(((("testing with " + location) + " := ") + value));
      final String scenario = (((("scenario scen load spec set " + location) + ":=") + value) + ";");
      final Scenario result = this.parseHelper.parse(scenario);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Unexpected errors: �errors.join(\", \")�");
      Assert.assertTrue(_builder.toString(), errors.isEmpty());
      Element _get = ((Scenario) result).getElements().get(0);
      Assert.assertEquals(((Set) _get).getLocation(), location.trim());
      Element _get_1 = ((Scenario) result).getElements().get(0);
      Assert.assertEquals(((Set) _get_1).getValue(), value);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
